### ISSUE TITLE
Code Review - Repository

### ISSUE THREAD

**Issue by veerleprins** [lisaoude/browser-technologies-2021#1]
### Repo:
- Good thing you have already deployed your site! ✅ 
- You do not yet have a README that already describes some of your project. 😢 
- Have you used some sources yet? Maybe you can already add it to your README by then.

### To Solve this Issue:

- [x] Write a description of your case.
- [x] Write a piece about the layers of your application (pleasurable, functional, etc.)
- [x] Add your wireflow to your README.
- [x] Put your livelink in your README as well.
- [x] Add the sources to the README.
- [x] Maybe you can describe your installation process.

**Comment by lisaoude** [comment]
Thanks for the feedback! 😄👍
